/**
 * Port allocations for all services in the dev environment
 */

module.exports = {
  // Coordinator Service
  COORDINATOR: 3500,

  // External Bridge Services
  EXTERNAL_BRIDGE_FETCHER_BINANCE: 3000,
  EXTERNAL_BRIDGE_FETCHER_KRAKEN: 3001,
  EXTERNAL_BRIDGE_WEBSOCKET_BINANCE: 3100,
  EXTERNAL_BRIDGE_WEBSOCKET_KRAKEN: 3101,

  EXTERNAL_BRIDGE_STORAGE: 3200,

  INTERNAL_BRIDGE_BINANCE_ORDERS_TRANSFORMER: 3300,
  INTERNAL_BRIDGE_BINANCE_TRADES_TRANSFORMER: 3301,

  INTERNAL_BRIDGE_KRAKEN_ORDERS_TRANSFORMER: 3310,
  INTERNAL_BRIDGE_KRAKEN_TRADES_TRANSFORMER: 3311,

  PY_PREDICTOR: 3400,
  // Monitoring Services
  PERSES: 8080,
  VICTORIA_METRICS: 8428,
};

