/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KeyValue {
  key: Buffer
  value: Buffer
}
export declare class SegmentedLog {
  constructor(path: string, enableCompression?: boolean | undefined | null)
  static openReadOnly(path: string, enableCompression?: boolean | undefined | null): SegmentedLog
  static openAsSecondary(primaryPath: string, secondaryPath: string, enableCompression?: boolean | undefined | null): SegmentedLog
  tryCatchUpWithPrimary(): void
  close(): void
  append(message: Buffer): Buffer
  appendBatch(messages: Array<Buffer>): Array<Buffer>
  put(id: number, value: Buffer): void
  iterateFrom(startId?: number | undefined | null): SegmentedLogIterator
  truncateBefore(id: number): void
  readLast(count?: number | undefined | null): Array<KeyValue>
  getLastKey(): Buffer | null
}
export declare class SegmentedLogIterator {
  next(): KeyValue | null
  hasNext(): boolean
  close(): void
}
