/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KeyValue {
  key: Buffer
  value: Buffer
}
export declare class SegmentedLog {
  constructor(path: string, enableCompression?: boolean | undefined | null)
  static openReadOnly(path: string, enableCompression?: boolean | undefined | null): SegmentedLog
  static openAsSecondary(primaryPath: string, secondaryPath: string, enableCompression?: boolean | undefined | null): SegmentedLog
  tryCatchUpWithPrimary(): void
  close(): void
  append(message: Buffer): Buffer
  appendBatch(messages: Array<Buffer>): Array<Buffer>
  put(key: Buffer, value: Buffer): void
  iterateFrom(startKey?: Buffer | undefined | null, batchSize?: number | undefined | null): SegmentedLogIterator
  truncateBefore(beforeKey: Buffer): void
  readLast(count?: number | undefined | null): Array<KeyValue>
  getLastKey(): Buffer | null
}
export declare class SegmentedLogIterator {
  next(): KeyValue | null
  nextBatch(): Array<KeyValue>
  hasNext(): boolean
  close(): void
}
