class SegmentedLogIterator:
    def next(self) -> tuple[bytes, bytes] | None: ...
    def next_batch(self) -> list[tuple[bytes, bytes]]: ...
    def has_next(self) -> bool: ...
    def close(self) -> None: ...


class SegmentedLog:
    def __init__(self, path: str, enable_compression: bool | None = None) -> None: ...
    @staticmethod
    def open_read_only(path: str, enable_compression: bool | None = None) -> "SegmentedLog": ...
    @staticmethod
    def open_as_secondary(
        primary_path: str,
        secondary_path: str,
        enable_compression: bool | None = None,
    ) -> "SegmentedLog": ...
    def try_catch_up_with_primary(self) -> None: ...
    def close(self) -> None: ...
    def append(self, message: bytes) -> bytes: ...
    def append_batch(self, messages: list[bytes]) -> list[bytes]: ...
    def put(self, key: bytes, value: bytes) -> None: ...
    def iterate_from(
        self, start_key: bytes | None = None, batch_size: int | None = None
    ) -> SegmentedLogIterator: ...
    def truncate_before(self, before_key: bytes) -> None: ...
    def read_last(self, count: int | None = None) -> list[tuple[bytes, bytes]]: ...
    def get_last_key(self) -> bytes | None: ...


class RocksDb:
    def __init__(self, path: str, enable_compression: bool | None = None) -> None: ...
    @staticmethod
    def open_as_secondary(
        primary_path: str,
        secondary_path: str,
        enable_compression: bool | None = None,
    ) -> "RocksDb": ...
    def try_catch_up_with_primary(self) -> None: ...
    def close(self) -> None: ...
    def put(self, key: bytes, value: bytes) -> None: ...
    def iterate_from(
        self, start_key: bytes | None = None, batch_size: int | None = None
    ) -> SegmentedLogIterator: ...
    def iterate_from_end(
        self, start_key: bytes | None = None, batch_size: int | None = None
    ) -> SegmentedLogIterator: ...
